#pragma once
enum ItemSlot {
	SLOT_ZBROJA, 
	SLOT_NARAMIENNIKI, 
	SLOT_REKAWICE, 
	SLOT_NAGOLENNIKI, 
	SLOT_BUTY, 
	SLOT_HELM, 
	SLOT_PREKA, 
	SLOT_LREKA,
	SLOT_KOSZULA,
	SLOT_SPODNIE,
	SLOT_SZATA,
	SLOT_PIERSCIENR,
	SLOT_PIERSCIENL,
	SLOT_NASZYJNIK,
	SLOT_ILOSC
};